### ISSUE TITLE
FeatherBoard errors

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#38]
It was working with 2.0.2 and in latest build now I get this error. I get the combatlevel through PlaceholderAPI.

[19:44:48] [Craft Scheduler Thread - 271/WARN]: [FeatherBoard] Plugin FeatherBoard v3.23.0 generated an exception while executing task 356
java.lang.NoSuchMethodError: com.gmail.mrphpfan.mccombatlevel.McCombatLevel.getCombatLevel(Lorg/bukkit/entity/Player;)Ljava/lang/Integer;
	at com.pixar02.papi.expansion.CombatLevelExpansion.onPlaceholderRequest(CombatLevelExpansion.java:107) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342) ~[?:?]
	at be.maximvdw.featherboardcore.placeholders.aB$1.a(PlaceholderAPIPlaceholder.java:36) ~[?:?]
	at be.maximvdw.featherboardcore.placeholders.aB$1.getResult(PlaceholderAPIPlaceholder.java:25) ~[?:?]
	at be.maximvdw.featherboardcore.placeholders.Placeholder.getPlaceholders(Placeholder.java:219) ~[?:?]
	at be.maximvdw.featherboardcore.a.d.a(AnimationStaticPart.java:49) ~[?:?]
	at be.maximvdw.featherboardcore.a.a.a(Animation.java:157) ~[?:?]
	at be.maximvdw.featherboardcore.a.a.a(Animation.java:47) ~[?:?]
	at be.maximvdw.featherboard.scoreboard.ScoreboardPart.updatePlaceholders(ScoreboardPart.java:316) ~[?:?]
	at be.maximvdw.featherboard.scoreboard.ScoreboardPart.access$000(ScoreboardPart.java:25) ~[?:?]
	at be.maximvdw.featherboard.scoreboard.ScoreboardPart$a.run(ScoreboardPart.java:302) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1209]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1209]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1209]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by games647** [comment]
>com.pixar02.papi.expansion.CombatLevelExpansion.onPlaceholderRequest

That plugin should be updated. There are some breaking changes in the last version. I added the old method back now.
